name: Evaluation

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check neptun.txt
        uses: akosdudas/ahk-action-neptuncheck@v1

      - name: Prepare .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.301"

      - name: Build sln
        run: dotnet build

      - name: Evaluate
        uses: docker://akosdudas/sflab-ahk:efrest-2021

      - name: Publish results
        uses: akosdudas/ahk-action-publish-result-pr@v1
        with:
          input-file: "result.txt"
          image-extension: ".png"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
